// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package nats

// Injectors from wiring.go:

func BuildModule() *module {
	natsApi := NewApi()
	natsModule := NewDB(natsApi)
	return natsModule
}
