// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package nats

import (
	"github.com/mvcatsifma/golang-module-walker/config"
)

// Injectors from wiring.go:

func BuildModule(config2 *config.AppConfig) *module {
	natsApi := NewApi()
	natsModule := NewDB(natsApi, config2)
	return natsModule
}
