// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package b

// Injectors from wiring.go:

func BuildModule() *module {
	bApi := NewApi()
	bModule := NewModule(bApi)
	return bModule
}
