// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package c

// Injectors from wiring.go:

func BuildModule() *module {
	cApi := NewApi()
	cModule := NewC(cApi)
	return cModule
}
