// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package c

import (
	"github.com/mvcatsifma/golang-module-walker/db"
)

// Injectors from wiring.go:

func BuildModule(db2 db.IDatabase) *module {
	cApi := NewApi()
	cModule := NewC(cApi, db2)
	return cModule
}
