// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package a

// Injectors from wiring.go:

func BuildModule() *module {
	aApi := NewApi()
	aModule := NewModule(aApi)
	return aModule
}
