// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package a

import (
	"github.com/mvcatsifma/golang-module-walker/db"
)

// Injectors from wiring.go:

func BuildModule(database db.IDatabase) *module {
	aApi := NewApi(database)
	aModule := NewA(aApi)
	return aModule
}
