// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package logging

import (
	"github.com/mvcatsifma/golang-module-walker/config"
)

// Injectors from wiring.go:

func BuildModule(config2 *config.AppConfig) *module {
	loggingApi := NewApi()
	loggingModule := NewConfig(loggingApi, config2)
	return loggingModule
}
