// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package db

// Injectors from wiring.go:

func BuildModule() *module {
	dbApi := NewApi()
	dbModule := NewDB(dbApi)
	return dbModule
}
