// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package root

// Injectors from wiring.go:

func BuildModule() *module {
	rootApi := NewApi()
	rootModule := NewModule(rootApi)
	return rootModule
}
